version: '3.8'

services:
  app:
    build: .
    container_name: product-info-extractor
    ports:
      - "8501:8501"
    volumes:
      - ./uploaded_images:/app/uploaded_images
      - ./extracted_info:/app/extracted_info
    environment:
      - ENVIRONMENT=production
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLE_CORS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3